version: "2.4"

services:
  #  Log into this container with : docker-compose exec express sh
  express:
    env_file: .env
    build:
      context: ./docker/nodejs/
      args:
        # Get the user id & group id of the owner of the project dir with "ls -la" and paste the result here. This will update the
        # project dir permission inside the container
        - HOST_USER=${HOST_USER}
        - HOST_USERGROUP=${HOST_USERGROUP}
    restart: unless-stopped
    container_name: express
    volumes:
      - ./:/home/docker:rw
    ports:
      - ${PORT}:${PORT}
    command: "npm run dev"

  redis:
    env_file: .env
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - ${REDIS_PORT}:6379

volumes:
  redis: {}
